//------------------------------------------------------------------------------
// This file is automatically generated by tools/generate-package-versions.js
// Do not edit this file manually
//------------------------------------------------------------------------------
export const packageVersions = {
  nx: '20.8.4',
  firebase: '10.10.0',
  firebaseAdmin: '11.11.1',
  firebaseFunctions: '4.8.2',
  firebaseFunctionsTest: '3.1.1',
  firebaseTools: '12.9.1',
  killPort: '2.0.1',
  nodeEngine: '18',
  googleCloudFunctionsFramework: '3.3.0',
}
