//------------------------------------------------------------------------------
// This file is automatically generated by tools/generate-package-versions.js
// Do not edit this file manually
//------------------------------------------------------------------------------
export const packageVersions = {
  nx: '16.8.1',
  firebase: '9.14.0',
  firebaseAdmin: '11.10.1',
  firebaseFunctions: '4.8.2',
  firebaseFunctionsTest: '3.1.0',
  firebaseTools: '12.4.5',
  killPort: '2.0.1',
  nodeEngine: '16',
  googleCloudFunctionsFramework: '3.3.0',
}
