//------------------------------------------------------------------------------
// This file is automatically generated by tools/generate-package-versions.js
// Do not edit this file manually
//------------------------------------------------------------------------------
export const packageVersions = {
  nx: '20.8.4',
  firebase: '12.8.0',
  firebaseAdmin: '13.6.0',
  firebaseFunctions: '7.0.3',
  firebaseFunctionsTest: '3.4.1',
  firebaseTools: '13.35.1',
  killPort: '2.0.1',
  nodeEngine: '18',
  googleCloudFunctionsFramework: '3.3.0',
}
