# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      # Ignore updates to these packages:
      - dependency-name: "@nx*"
      - dependency-name: "@swc*"
      - dependency-name: "@types/*"
      - dependency-name: "@typescript*"
      - dependency-name: "eslint*"
      - dependency-name: "jest*"
      - dependency-name: "nx*"
      - dependency-name: "prettier*"
      - dependency-name: "ts-jest"
      - dependency-name: "ts-node"
      - dependency-name: "tslib"
      - dependency-name: "typescript"
      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
