# Create a draft Github release for newly tagged versions
# Triggered by `npm run version -- v1.2.3`
# Package is published to npm when this release is published
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    needs: [publish_github, publish_npm]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
